name: SimpleDBMT
main: io.github.SebastianDanielFrenz.SimpleDBMT.adapter.SimpleDBMT2BukkitAdapter
version: 2.0.0
author: SebastianDanielFrenz
commands:
  simpledbmt:
    desciption: The main SimpleDBMT command.
    alias: [db]